spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
server:
  port: 8999

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/