spring:
  application:
    name: Eureka-Server
  profiles:
      active: dev  
server: 
   port: 8888
   
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
     waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
   