spring:
  application:
    name: Eureka-Server
  profiles:
      active: dev  
server: 
   port: 8761
   
eureka:
  client:
   registerWithEureka: false
   fetchRegistry: false
   server:
     waitTimeInMsWhenSyncEmpty: 0
   instance:
      hostname: localhost 

debug: true     
   