spring:
  application:
    name: user-service
  profiles:
      active: dev  
server: 
   port: 9001

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/   